PyRigi/PyRigi

doc/conf.py, doc/userguide/api.md, doc/userguide/api/datatype.md, pyrigi/data_type.py
Documentation of Vertex, Edge and Point added.
They can be linked using `` :obj:`pyrigi.data_type.Vertex` `` in general, but setting 
```python
autodoc_type_aliases = {
"Vertex": ":obj:`pyrigi.data_type.Vertex`",
"Edge": "Edge",
"Point": "Point", 
}
```
in `conf.py` does not create the link correctly. So I propose we just keep it without linking.
=> documentation of the types

doc/development/cheatsheet.md, pyrigi/framework.py, pyrigi/graph.py, test/test_framework.py
- `complete_graph` and `complete_graph_on_vertices` renamed using CamelCase since they serve as class constructors.
- `dim` parameter removed from `Framework.__init__` since the dimension is anyway retrieved from the points of realization. The only case when this is not possible is when the empty graph is passed, then the dimension is set to 0. To get empty framework with different dimension, Framework.Empty(dim) can be used.
=> Feature constructors

pyrigi/framework.py, pyrigi/graph.py, test/test_framework.py, test/test_graph.py
Since some method names can get lengthy (minimally k-vertex redundantly globally rigid), we could use `inf`, `min`, `max` instead of `infinitesimally`, `minimally`,`maximally` respectively.
=> method names shortened

.github/workflows/python-test.yml
With this PR we create automated tests that are run whenever there is a pull request into main or dev.
The tests are:
* `flake8` to check for errors and syntax compliance to PEP8 (except to errors F401,F541,F841,W605,E203,E501,E701, so in particular line length E501 is not checked)
* `pytest`
To ensure compliance to PEP8, one can use `black`  on the `.py` files.
If this PR is accepted, we will provide information on how to automate the use of `black` at each commit.
=> GitHub Action to test the code with flake8 and pytest for PR into dev and main

pyrigi/framework.py, pyrigi/graph.py, test/test_graph.py
- `__str__` simplified using vertex/edge_list which are now sorted if possible
- `__repr__` calls `__str__` which allows to get output without `print`:
```python
>>> from pyrigi import Graph
>>> G = Graph.from_vertices([3, 1, 7, 2, 12, 3, 0])
>>> G
Graph with vertices [0, 1, 2, 3, 7, 12] and edges []
```
=> __str__, __repr__ of Graph and Framework

.github/workflows/gh-pages.yml, .github/workflows/python-test.yml, .gitignore, README.md, doc/development/howto.md, doc/requirements.txt, doc/userguide/getting_started.md, pyproject.toml, requirements.txt
Migrating to poetry simplifies keeping track of dependencies (runtime, dev, doc).
Poetry also makes easier to work with a virtual python environment dedicated to PyRigi.
Moreover, it should allow easy publication to PyPi.
=> Poetry migration

doc/userguide/api/misc.md
The link to `misc.is_zero_vector` should work now as there is a page generated from `misc.md`.
=> Missing misc.md file added

doc/development/howto.md, doc/userguide/tutorial.md
When using poetry, one has to install jupyterlab manually to be able to use it in the environment created by poetry. Shall we add jupyterlab as a dev dependency, or keep it only mentioned in the documentation as in the commit?
Similarly with Jupytext that is necessary for opening `.md` tutorials as notebooks.
=> Doc jupyterlab/jupytext

pyrigi/graph.py
Do we want to be able to check whether two graphs are equal like `G == H`? This can be done in Python by implementing method `__eq__`, see the first commit of this branch. I think it would be useful for instance in tests.
If yes, when do we consider two graphs to be equal? Same vertex and edge sets? Could it happen in future that we have for instance some edge labelings?
=> Equality of graphs

pyrigi/graph_drawer.py
Edges incident with the selected vertex were drawn with the previous value of edge width when just pressed on a vertex without dragging if the edge width value was changed. Fixed this by updating the edge width value of layer 1 instead of layer 3(there are no edges in layer 3).
=> Added missing edge width update for layer 1

.github/workflows/gh-pages.yml, doc/userguide/tutorials/framework_database.md, doc/userguide/tutorials/graph_basics.md, doc/userguide/tutorials/plotting.md, poetry.lock, pyproject.toml
To goal is to generate `.ipynb` versions of the tutorial notebooks so a user can download them via the online documentation.
=> Links to .ipynb notebooks of tutorials

doc/index.md, doc/userguide/getting_started.md, doc/userguide/installation_guide.md
Added detailed installation instructions based on today's installation session to the PyRigi documentation. The Windows instructions seemed to work on all (non-restricted) machines. I guess for machines restricted by the university, we do not need to provide instructions, as that probably works best on a case-by-case basis.
=> Detailed Installation Instructions created in the documentation

pyrigi/framework.py
Created an easy example for the usage of `Framework.Empty()`
=> Example for the empty Framework

pyrigi/graph.py, test/test_graph.py
This fixes a bug discovered by Tony and a wrong call of `is_connected`.
Basic tests for dimension 1 and 2 are added.
=> Two bugs in is_Rd_circuit fixed

pyrigi/graph_drawer.py
This bug arises during keyboard events (debug log on jupyter).
=> Bug - requesting pointer position on keyboard events

doc/math/graph-theory/known-families.md, doc/math/rigidity.md, doc/math/rigidity/global.md, doc/math/rigidity/infinitesimal.md, pyrigi/framework.py
Moreover, `is_isostatic` was referenced, but wasn't implemented yet, so I created a corresponding method.
=> Added missing methods to the docs

.github/workflows/gh-pages.yml, .github/workflows/python-test-main.yml, doc/conf.py, pyrigi/framework.py
This PR applies the fix #182 also to `dev`. Moreover, the setting of doc compilation is changed so that an error is raised when a compilation of a tutorial notebook fails. This doc compilation now has to pass without errors also when we merge to `main`.
=> Test notebook execution

contributors.md
For some reason, the previous merge duplicated contributors to 0.3.
=> Duplicate section removed

doc/math/rigidity/generic.md, doc/userguide/tutorials/framework_database.md, pyrigi/data_type.py, pyrigi/framework.py, pyrigi/frameworkDB.py, pyrigi/graph.py, pyrigi/graphDB.py, pyrigi/graph_drawer.py, pyrigi/misc.py, pyrigi/motion.py, test/test_framework.py, test/test_graph.py
+ Added missing 1-line comments
+ `d` -> `dim` for consistency
+ PEP 545: `Dict`, `List`, `Union` are deprecated. Now `dict`, `list`, `|` are generic types. For the input type, we should be able to deal with a `Sequence` instead of specifying `list | tuple`, while for the output type, we should specify exactly what the output is, e.g. `list`.
=> Refactor the codebase: consistent using of dim, type hinting

pyrigi/framework.py, pyrigi/graph.py
The removal of non-public methods related to plotting shall be done when refactoring plotting to avoid conflicts.
=> Non-public methods removed from lists

doc/conf.py, doc/userguide/tutorial.md, doc/userguide/tutorials/motion.md, doc/userguide/tutorials/plotting.md, pyrigi/misc.py, pyrigi/motion.py, test/test_motion.py
+ Implemented the numerical `ApproximateMotion` class. It depends on a naive implementation of homotopy continuation. 
+ Moved the methods `_normalize_realizations` and `animate` to the parent `Motion` class, that both `ParametricMotion` and `ApproximateMotion` depend on
=> Added `ApproximateMotion` class

pyrigi/_pebble_digraph.py, pyrigi/framework.py, pyrigi/frameworkDB.py, pyrigi/graph.py, test/test_graph.py
- `spanning_sparse_subgraph`  renamed to `spanning_kl_sparse_subgraph`, a test of the method added
- minors todos fixed
- construction `if v in Graph.nodes` replaced by `if Graph.has_node(v)` since the former raises `TypeError` when called on non-hashable
=> Renaming, minor todos and refactoring to has_node

doc/development/howto/testing.md, pyrigi/framework.py, pyrigi/motion.py, test/test_framework.py
On some machines, one had to close animations manually when running `pytest`. They close automatically now.
Also the command for excluding optional packages for pytest was fixed: now also the test marked as `slow_main` or `long_local` are skipped.
=> Animation closed immediately in pytest

doc/development/howto/input_checks.md, doc/userguide/api.md, doc/userguide/api/datatype.md, doc/userguide/api/exception.md, doc/userguide/api/framework.md, doc/userguide/api/frameworkDB.md, doc/userguide/api/graph.md, doc/userguide/api/graphDB.md, doc/userguide/api/graphdrawer.md, doc/userguide/api/misc.md, doc/userguide/api/motion.md, doc/userguide/api/plot_style.md, pyrigi/_input_check.py, pyrigi/exception.py, pyrigi/frameworkDB.py, pyrigi/graphDB.py, pyrigi/misc.py, pyrigi/warning.py
In some cases, we listed items to be displayed in the documentation explicitly, now they are added automatically using `automodule`. Moreover, a page with exceptions and warnings has been added and some docstrings have been improved.
The `:undoc-members:` setting has been removed to display only methods etc. that have a docstring. Hence, `make html coverage` discovers the missing ones now.
=> Missing items displayed in the documentation

.github/workflows/python-test-dev.yml, .github/workflows/python-test-main.yml, doc/development/howto/dependencies.md, doc/development/howto/documentation.md, doc/development/howto/style_guide.md, doc/development/howto/testing.md, doc/userguide/installation.md
Enforcing Sphinx warnings to fail the testing of doc compilation should help to avoid problems with links or badly formatted docstrings that we have been getting time to time unnoticed.
=> GitHub tests require no sphinx warnings

doc/math/rigidity/second-order.md, pyrigi/framework.py, pyrigi/frameworkDB.py, pyrigi/graph.py, pyrigi/misc.py, pyrigi/motion.py, test/test_framework.py, test/test_frameworkDB.py, test/test_misc.py
I suggest to make some misc functions non-public as their usage is just within the package itself.
Also, I propose to avoid names in function names.
=> Make some misc functions non-public

doc/development/howto/git.md
I propose to introduce predefined prefixes of PRs in order to have better Release notes [(see 1.0.0 and 1.0.1)](https://github.com/PyRigi/PyRigi/releases) with reasonable amount of work.
The (usage of) branch prefixes is also adjusted.
A script for automatic grouping the PRs according to prefixes will be provided once there are enough prefixed PRs to create and test it.
=> Guide: Added guide on PR prefixes and release notes

.github/workflows/python-test-dev.yml, .github/workflows/python-test-main.yml, doc/development/howto/testing.md
It happened that the tests on #309 were running for more than 4 hours without finishing, see https://github.com/PyRigi/PyRigi/actions/runs/14254585226/attempts/1. After cancellation and re-running, they passed. Besides investigating what the problem was, I suggest setting a timeout for the tests to avoid such long runs, where something is obviously going wrong.
=> Setup: Added testing timeouts

doc/conf.py, doc/development/howto/git.md, pyproject.toml
Since on #324, not the latest version of `main` was merged, `main` is merged to `dev` again.
=> Setup: Release 1.0.2 (pulled `main` to `dev`)

pyrigi/framework.py
Previously, files were saved as `.png.png`
=> Fix: Removed suffix duplication in `plt.savefig`

pyrigi/framework/_general.py, pyrigi/framework/_plot/plot.py, pyrigi/framework/_rigidity/infinitesimal.py, pyrigi/framework/_rigidity/second_order.py, pyrigi/framework/_transformations/transformations.py, test/motion/test_approximate_motion.py
Whenever possible, `framework.dim` and `framework[v]` is used instead of `framework._dim` and `framework._realization[v]` respectively in functions accepting `framework: FrameworkBase`.
=> Code: Used public attributes of `FrameworkBase`

doc/userguide/api/motion.md, doc/userguide/tutorials/motion.md
By splitting `motion.py` into separate files, the documentation of `ApproximateMotion` and `ParametricMotion` stopped being rendered in API Reference/Motions. This is fixed now.
Also, a missing download link is added.
=> Doc: Fixed missing documentation of `Approximate` and `ParametricMotion`

doc/userguide/tutorials/rigidity.md
+ Added explanation that strings should be used to create sympy coordinates
=> Fix: Corrected example in Tutorial about symbolic flexes
