PyRigi/PyRigi

doc/conf.py, doc/development/cheatsheet.md, doc/development/index.md, pyrigi/framework.py
- tables for cross-referencing
- code of sample definition
=> Current content of cheatsheet structured

README.md, doc/conf.py, pyrigi/framework.py, requirements.txt, test/test_framework.py, test/test_graph.py, test/test_matroid.py
Also bugfix in trivial_inf_flexes and requirements.txt with networkx , matplotlib and sympy.
=> Tests and conf blackened

.flake8, .github/workflows/python-test.yml, pyrigi/__init__.py, pyrigi/data_type.py, pyrigi/framework.py, pyrigi/graph.py, pyrigi/matroid.py, test/test_framework.py, test/test_matroid.py
This PR solves some errors in the code which were ignored before and enforces stricter rules.
Moreover, it sets the configuration of flake8 via the file .flake8.
=> Stricter rules

.github/workflows/python-test.yml, requirements.txt
=> Enforced tests from docstrings.

doc/conf.py, doc/development/howto.md, doc/requirements.txt, doc/userguide/tutorial.md, doc/userguide/tutorials/basic.md, doc/userguide/tutorials/graph_basics.md, doc/userguide/tutorials/jupytext.toml, pyrigi/graph.py
Tutorials can be now written using notebooks and rendered in the documentation.
=> Jupyter notebooks in the doc

doc/development/cheatsheet.md, doc/math/definitions.md, pyrigi/framework.py, test/test_framework.py
- setters and getters for realization simplified
- underlying_graph removed (Framework.graph() kept)
=> Some aliases removed

doc/development/howto.md, pyrigi/framework.py, pyrigi/graph.py
Some docstring were also reformatted.
=> Todos added to docstrings

pyrigi/graph.py, test/test_graph.py
The functions `min_rigid_subgraphs` and `max_rigid_subgraphs` have been rewritten to speed up the testing.
=> Speeding up min and max rigid subgraphs

doc/development/cheatsheet.md, doc/math/definitions.md, doc/refs.bib, pyrigi/graph.py, pyrigi/graphDB.py, test/test_graph.py
Conditions on edge count in redundancy checking and testing for redundancy added.
=> Feature redundancy

doc/userguide/api.md, doc/userguide/api/graphdrawer.md, poetry.lock, pyproject.toml, pyrigi/__init__.py, pyrigi/graph_drawer.py, pyrigi/graphdrawer.py
This feature (module) allows to construct graphs and 2D frameworks on screen using mouse and keyboard inputs.
=> Feature graphdrawer

README.md, doc/index.md, doc/userguide/api/graphdrawer.md, doc/userguide/getting_started.md, doc/userguide/tutorials/framework_database.md, doc/userguide/tutorials/graph_basics.md, doc/userguide/tutorials/plotting.md, pyrigi/graph_drawer.py
Besides mentioning `pip`, some minor problems are also fixed.
=> Pip installation in the documentation

.github/workflows/gh-pages.yml, doc/conf.py, doc/userguide/getting_started.md, doc/userguide/tutorials/framework_database.md
I have improved a bit the Getting started section. Now it is generated from a notebook.
=> Getting started

doc/userguide/installation_guide.md
=> Docs fixing installation guide

pyrigi/framework.py
Added an example in the documentation for the classmethod Collinear for Frameworks
=> Doc collinear

doc/index.md, doc/math/matroid_theory.md
From Anthony Nixon's contribution.
=> Matroidal notions for rigidity theory.

doc/math/graph-theory/known-families.md, doc/math/graph_theory.md, doc/userguide/tutorials/framework_database.md, pyrigi/framework.py, pyrigi/frameworkDB.py, pyrigi/graphDB.py, test/test_framework.py
=> Added Examples and Tests for `rigidity_matrix_rank` (including n-Frustum)

pyrigi/framework.py, pyrigi/graph.py, test/test_graph.py
Alison and Rebecca provided a multitude of examples, some of which I recycled as tests.
=> Many new examples and tests added to resolve TODO

poetry.lock, pyproject.toml, pyrigi/graph.py
Feature is there. Probably documentation need some improvement.
=> Feature realization number

contributors.md, doc/development/contributors.md, doc/index.md
The list of contributors is now displayed in the Development Guide.
=> Contributors in the documentation

doc/math/graph-theory/known-families.md, pyrigi/graphDB.py, test/test_framework.py
I have improved the linking between the source and the documentation and distributed the tests into existing ones.
Before we merge, we should fix the definition, since it does not determine the graph uniquely: the following one satisfies the definition as well. I think that what you want is the cartesian product of n-cycle and an edge, don't you?
=> Refactor frustum

.gitignore, pyrigi/framework.py
First draft to be reviewed, please @Legersky 
Yet to be done before the pull:
- add tests 
- add docs
=> Feature Onshape - generate models for 3D printing

pyrigi/framework.py, pyrigi/misc.py, test/test_framework.py, test/test_misc.py
implemented plotting for dimensions higher than 2 using two orthonormal vectors.
=> Feature high dimensional plotting

pyrigi/data_type.py, pyrigi/graph.py, test/test_graph.py
The handles Tony's request about the maximum rigid dimension.
=> Added `Graph` method `max_rigid_dimension`

pyrigi/motion.py
This feature creates the Motion and parametric motion classes.
ParametricMotion class does not have any tests yet, they will be added in a separate pull request later.
=> Motion and ParametricMotion class

pyrigi/motion.py, test/test_motion.py
added tests for check_edge_lengths and realization methods of ParametricMotion class
=> Feature ParametricMotion tests

doc/_static/thm.css, doc/conf.py
customized style for theorems, lemmas, definitions and algorithms in the doc
=> Doc colors

doc/math/rigidity/redundant.md, pyrigi/graph.py
=> restructuring into subsections

doc/math/rigidity/generic.md, pyrigi/graph.py, test/test_graph.py
+ Removed `min_rigid_subgraphs` due to lacking usefulness
+ Added tests
+ Added definition
=> Refactor minimal rigid subgraphs

pyrigi/framework.py, pyrigi/graph.py, test/test_framework.py
I also used this branch to refactor the documentation and type hinting slightly to incorporate the recommended types from the `typing` package instead of directly inferring types.
=> Added functionality for symbolic edge lengths

pyrigi/graph.py, test/test_graph.py
+ Added implementation for `dim=3`
+ Added Tests
+ Minor refactoring
=> Refactoring `is_Rd_circuit`

doc/userguide/tutorials/plotting.md, pyrigi/framework.py, pyrigi/graph.py
+ Added a plotting method for equilibrium stresses.
+ Added improved 1D (and collinear) plotting capabilities via the `connection_style` Parameter.
=> Added a plotting method for equilibrium stresses

pyrigi/frameworkDB.py, test/test_framework.py
Relevant commits picked from `refactor-framework-db`:
+ Fixed bug with `K33plusEdge`
+ Added some 3D frameworks for `test_framework`
=> Refactor framework db

doc/conf.py, doc/development/howto.md, pyrigi/framework.py, pyrigi/frameworkDB.py, pyrigi/graph.py, pyrigi/graphDB.py, pyrigi/graph_drawer.py
Replaced by `Suggested Improvements`
=> Refactor `ToDo`s

doc/development/howto.md, test/test_data_type.py, test/test_framework.py, test/test_graph.py, test/test_motion.py, test/test_pebble_digraph.py
Test naming convention is proposed and applied.
=> Test names unified

doc/userguide/tutorials/plotting.md, pyrigi/data_type.py, pyrigi/framework.py, pyrigi/graph.py, test/test_framework.py, test/test_graph.py
+ Plotting capability now exists in `Framework`
+ Moved Parameters to public methods `plot2D` and `plot3D` so that they can be displayed
+ Slightly improved docstrings
+ Added methods `plot_inf_flex` and `plot_stress`
+ Adjusted documentation
=> Refactor plotting functionality

pyrigi/_plot.py, pyrigi/framework.py
I propose to move the non-public plot functions to a separate non-public file.
=>  Non-public plot functions in a separate file

doc/development/cheatsheet.md, doc/development/howto.md, doc/math/graph-theory/double-banana.md, doc/math/graph-theory/known-families.md, doc/math/graph_theory.md, doc/math/rigidity/generic.md, doc/math/rigidity/global.md, doc/math/rigidity/realizations.md, doc/math/rigidity/redundant.md, doc/refs.bib, pyrigi/graph.py
applied sorting to bib file and added text to howto on the labeling standard
=> Refactor bib labels

test/test_graph.py
In particular adding `slow_main` where necessary and added more `K66_minusPerfectMatching` tests
=> Minor `test_graph` refactoring

doc/userguide/api.md, doc/userguide/api/plot_style.md, doc/userguide/tutorials/plotting.md, pyrigi/_plot.py, pyrigi/framework.py, pyrigi/graph.py, pyrigi/plot_style.py
The new class `PlotStyle` allows to pass easily style parameters for plotting while keeping the option to use keyword parameters directly.
=> PlotStyle introduced

pyrigi/framework.py, pyrigi/plot_style.py
Centroid and semicolon changed.
=> Minor refactoring of `PlotStyle`

doc/math/graph-theory/examples.md, doc/math/graph_theory.md, doc/math/matroid_theory.md
+ Moved general matroid theory definitions to `matroid_theory.md`
+ Moved graph theoretical definitions to `graph-theory.md`
=> Refactored `examples.md`

doc/math/rigidity/infinitesimal.md, doc/userguide/getting_started.md, doc/userguide/tutorial.md, doc/userguide/tutorials/graph_basics.md, doc/userguide/tutorials/plotting.md, doc/userguide/tutorials/rigidity.md, doc/userguide/tutorials/rigidity_tutorial.md, pyrigi/framework.py
+ Jan's rigidity tutorial with PyRigi added
=> Added Rigidity Tutorial

pyrigi/framework.py, test/test_framework.py, test/test_graph.py
- direct comparison of `Graph`s instead of their strings
- set of `frozenset`s used instead of permuting lists
=> Refactor test_graph

doc/development/howto.md, doc/userguide/getting_started.md, doc/userguide/installation_guide.md, doc/userguide/tutorials/rigidity.md, pyrigi/graph.py, pyrigi/plot_style.py
- Two doc compilation warnings solved
- parameter `combinatorial` changed to `algorithm` also in tutorials
=> Fix doc issues

pyrigi/_input_check.py, pyrigi/_pebble_digraph.py, pyrigi/framework.py, pyrigi/graph.py, pyrigi/graph_drawer.py, pyrigi/misc.py, pyrigi/motion.py
- some outputs are retyped to comply with indicated return type
- some signatures are adjusted to our usage of these methods
- mutable default argument avoided to prevent troubles they might cause
- a few other minor changes
=> Input and return types fixed

pyrigi/graph_drawer.py
Uncommented the output displaying line.
=> uncomment output displaying line

doc/remove_skip_execution_magic.py, pyrigi/frameworkDB.py, pyrigi/graphDB.py, test/test_framework.py, test/test_frameworkDB.py, test/test_graph.py, test/test_graphDB.py
+ Added `Icosahedral` and `Dodecahedral` to `graphDB`
+ Added `Icosahedron` and `Dodecahedron` to `frameworkDB`
=> Added the icosahedron and dodecahedron

doc/userguide/tutorials/plotting.md, pyrigi/plot_style.py, test/test_plot_style.py
+ also tests of PlotStyle(2/3D) are added
=> Attributes of PlotStyle(2/3D) changed into properties

pyrigi/exception.py, pyrigi/graph.py, test/test_graph.py
Default algorithms set up for every dimension. This includes renaming `combinatorial` to `graphic`, `sparsity` etc.
=> Default algorithms

pyrigi/graph.py, pyrigi/misc.py, pyrigi/motion.py, test/test_framework.py, test/test_graph.py, test/test_misc.py, test/test_motion.py
+ Removed redundant code
+ Added new tests to cover missing cases
=> Increased test coverage

pyrigi/_pebble_digraph.py, pyrigi/_plot.py, pyrigi/exception.py, pyrigi/framework.py, pyrigi/graph.py, pyrigi/graph_drawer.py, pyrigi/misc.py, pyrigi/motion.py, pyrigi/warning.py
+ Added Parameters and Definitions where these points fit.
+ Improved documentation of (private) methods
=> Improve documentation

test/test_graph.py
This further increases the test coverage.
=> Added two $K_4$ graphs glued in a vertex to `is_Rd_circuit` test

pyrigi/_plot.py, pyrigi/framework.py, pyrigi/misc.py, pyrigi/motion.py, test/test_framework.py, test/test_misc.py, test/test_motion.py
+ refactored `misc.eval_sympy_vector` to allow simple expressions as well
+ Replaced all occurances on `dev` of `evalf` by `misc.eval_sympy_expression`
=> Moved evaluation of sympy expressions to `misc.eval_sympy_expression`

pyproject.toml, pyrigi/framework.py, pyrigi/misc.py, pyrigi/motion.py, pyrigi/warning.py, test/test_framework.py, test/test_motion.py
+ Added randomization of equation to deal with stressed frameworks
+ Added a least squares approach for selecting the next infinitesimal flex
=> General approximate motions

doc/userguide/tutorials/framework_database.md, pyrigi/frameworkDB.py, pyrigi/graphDB.py, pyrigi/motion.py, test/test_framework.py, test/test_frameworkDB.py, test/test_graph.py, test/test_graphDB.py, test/test_motion.py
+ Renamed `CnSymmetricFourRegularWithFixedVertex`
+ Made method `ParametricMotion.check_edge_lengths` private
=> Renamed methods in `frameworkDB` and `ParametricMotion`

pyrigi/motion.py, test/test_framework.py, test/test_motion.py
+ Parametrized several of the tests
=> Refactor the `test_motion`

pyrigi/framework.py, test/test_framework.py
+ Used numerical inf_flexes capability
+ Added coned cube as example for is_prestress_stable
=> Refactor numerical part of `is_prestress_stable`

pyrigi/_plot.py, pyrigi/framework.py, test/test_framework.py
+ Added appropriate tests
+ Refactored a few docstrings
=> Added numerical option to `Framework.stresses()`

doc/userguide/tutorials/graph_basics.md, pyrigi/_input_check.py, pyrigi/graph.py, pyrigi/graphDB.py, test/test_graph.py, test/test_graphDB.py
+ Added `_input_check.equal`
+ Moved `Graph.CompleteOnVertices` to `graphDB.Complete`
+ Changed documentation
+ Added test to `test_graphDB`
=> Move `Graph.CompleteOnVertices` to `graphDB.Complete`

doc/math/graph-theory/examples.md, doc/math/matroid_theory.md, doc/math/rigidity/generic.md, doc/math/rigidity/global.md, doc/math/rigidity/redundant.md, doc/refs.bib
fixed definition on linked pairs
added details on references
fixed labeling in bib
=> Docfix linked pairs + refs

pyrigi/graphDB.py
=> Fixed input check in DoubleBanana.

doc/math/graph_theory.md, doc/refs.bib, pyrigi/_pebble_digraph.py, pyrigi/graph.py, pyrigi/graphDB.py, test/test_graph.py
Allowed loops in sparsity check and fixed a bug related to this and another related to vertex names.
=> Fix: Fixed and allowed usage of loops for sparsity

pyrigi/framework.py, test/test_framework.py
+ Methods added
+ Corresponding tests added
=> Feature: Added the method `rotate3D` and the alias `rotate`

doc/conf.py, pyrigi/framework/framework.py, test/framework/test_framework.py
For creating print-quality images without changing the appearance (which `canvas_width` and `canvas_height` would do)
=> Added option for specifying the `dpi` in `plot2D` and `plot3D`

pyrigi/graph_drawer/graph_drawer.py
+ Added the option to change the vertex label size via a slider 
+ Added a button to clear the entire canvas
+ Added animation in the GUI when a vertex is selected for drawing an edge that makes the vertex lighter
=> Added new features to the `GraphDrawer`
